# Generated by Django 4.0.5 on 2022-06-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiPage',
            new_name='DjangoWikiPage',
        ),
    ]
