# Generated by Django 4.0.5 on 2022-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_rename_wikipage_djangowikipage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoWikiPage',
            new_name='DjangoSoftwareWikiPage',
        ),
    ]
